<?php

declare(strict_types=1);

namespace App\Document\Service;

use App\Document\DocumentGenerator as DocumentGeneratorContract;
use App\Document\Entity\Document;
use App\Document\Entity\DocumentType;
use App\Document\Entity\DocumentVersion;
use App\Document\Entity\Enum\DocumentEntityType;
use App\Document\Entity\Enum\DocumentOwnerRole;
use App\Document\Entity\Enum\DocumentScope;
use App\Document\Entity\Enum\DocumentVisibility;
use App\Document\Storage\FileStorage;
use App\Shared\Audit\AuditService;
use App\Shared\Exception\ConflictException;
use Doctrine\ORM\EntityManagerInterface;
use Symfony\Component\Uid\NilUuid;
use Symfony\Component\Uid\Uuid;

/**
 * Реализация публичного контракта авто-генерации документов (FR-1.2.8).
 * См. App\Document\DocumentGenerator. Алиас импорта — имя класса совпадает
 * с именем интерфейса (PHP запрещает объявление класса с именем, занятым `use`).
 *
 * - ensureDocumentType(): идемпотентная регистрация auto_generated-типа
 *   (owner_role=system). Админский API такие типы не создаёт — авто-генерация
 *   только через плагин;
 * - generate(): документ от имени системы (owner_role=system,
 *   is_auto_generated=true), версия + контент в FileStorage, аудит
 *   document.auto_generated. Повтор для той же (тип, сущность) возвращает
 *   существующий документ — идемпотентность (NFR-5, at-least-once события).
 *
 * Актёра-пользователя у системы нет: created_by/uploaded_by = NilUuid.
 */
final readonly class DocumentGeneratorService implements DocumentGeneratorContract
{
    public function __construct(
        private EntityManagerInterface $em,
        private FileStorage $storage,
        private AuditService $audit,
    ) {
    }

    public function ensureDocumentType(
        string $code,
        string $name,
        DocumentOwnerRole $ownerRole,
        DocumentVisibility $visibility,
        bool $required = false,
        int $sortOrder = 0,
    ): DocumentType {
        $code = trim($code);
        if ('' === $code) {
            throw new ConflictException('Document type code is required');
        }

        $existing = $this->em->getRepository(DocumentType::class)->findOneBy(['code' => $code]);
        if (null !== $existing) {
            return $existing;
        }

        $type = new DocumentType(
            code: $code,
            name: trim($name),
            ownerRole: $ownerRole->value,
            visibility: $visibility->value,
            required: $required,
            sortOrder: $sortOrder,
        );
        $type->setAutoGenerated(true);

        $this->em->persist($type);
        $this->em->flush();

        $this->audit->record(
            action: 'document_type.auto_generated',
            entityType: 'document_type',
            entityId: (string) $type->getId(),
            actorType: 'system',
            after: ['code' => $type->getCode(), 'name' => $type->getName(), 'auto_generated' => true],
        );

        return $type;
    }

    public function generate(
        string $documentTypeCode,
        DocumentEntityType $entityType,
        Uuid $entityId,
        string $title,
        string $content,
        string $mimeType,
        string $extension,
        Uuid $tenantId,
        ?DocumentVisibility $visibility = null,
        ?string $ip = null,
    ): Document {
        $type = $this->resolveAutoGeneratedType($documentTypeCode);

        // Идемпотентность (NFR-5): для той же (тип, сущность) документ уже
        // сгенерирован — повторная доставка события не плодит дубликаты.
        $existing = $this->findByTypeAndEntity($type, $entityType, $entityId);
        if (null !== $existing) {
            return $existing;
        }

        $systemId = new NilUuid();
        $storagePath = $this->storage->store($content, (string) Uuid::v4(), $extension);

        $document = new Document(
            documentType: $type,
            entityType: $entityType,
            entityId: $entityId,
            title: $title,
            ownerRole: DocumentOwnerRole::SYSTEM,
            visibility: $visibility ?? DocumentVisibility::tryFrom($type->getVisibility()) ?? DocumentVisibility::PRIVATE,
            scope: $this->scopeFor($entityType),
            tenantId: $tenantId,
            createdBy: $systemId,
        );
        $document->setAutoGenerated(true);

        $version = new DocumentVersion(
            document: $document,
            version: $document->nextVersionNumber(),
            sha256: hash('sha256', $content),
            sizeBytes: \strlen($content),
            mimeType: $mimeType,
            originalName: $title,
            storagePath: $storagePath,
            uploadedBy: $systemId,
        );
        $document->addVersion($version);

        $this->em->persist($document);
        $this->em->persist($version);
        $this->em->flush();

        $this->audit->record(
            action: 'document.auto_generated',
            entityType: 'document',
            entityId: (string) $document->getId(),
            tenantId: (string) $tenantId,
            actorType: 'system',
            after: [
                'document_type' => $type->getCode(),
                'entity_type' => $entityType->value,
                'entity_id' => (string) $entityId,
                'title' => $title,
                'sha256' => $version->getSha256(),
                'size_bytes' => $version->getSizeBytes(),
                'visibility' => $document->getVisibility()->value,
            ],
            ip: $ip,
        );

        return $document;
    }

    /**
     * Тип документа по коду: должен существовать, быть активным и
     * auto_generated (только плагин, FR-1.2.8).
     *
     * @throws ConflictException если тип не найден/деактивирован/не auto_generated
     */
    private function resolveAutoGeneratedType(string $code): DocumentType
    {
        /** @var DocumentType|null $type */
        $type = $this->em->getRepository(DocumentType::class)->findOneBy(['code' => $code]);
        if (null === $type) {
            throw new ConflictException(\sprintf('Document type "%s" not found (register via ensureDocumentType)', $code));
        }

        if (!$type->isActive()) {
            throw new ConflictException(\sprintf('Document type "%s" is not active', $code));
        }

        if (!$type->isAutoGenerated()) {
            throw new ConflictException(\sprintf('Document type "%s" is not auto-generated (FR-1.2.8)', $code));
        }

        return $type;
    }

    /**
     * Существующий авто-генерируемый документ для (тип, сущность) или null.
     */
    private function findByTypeAndEntity(DocumentType $type, DocumentEntityType $entityType, Uuid $entityId): ?Document
    {
        /** @var Document|null $document */
        $document = $this->em->getRepository(Document::class)->findOneBy([
            'documentType' => $type,
            'entityType' => $entityType,
            'entityId' => $entityId,
        ]);

        return $document;
    }

    /**
     * Область привязки документа по типу сущности (AM-8): договор — scope
     * contract, всё остальное (тендер/лот/заявка/претензия) — tender.
     */
    private function scopeFor(DocumentEntityType $entityType): DocumentScope
    {
        return DocumentEntityType::CONTRACT === $entityType
            ? DocumentScope::CONTRACT
            : DocumentScope::TENDER;
    }
}
