<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * P1: унификация надёжной доставки — удаление механизма MessageTask.
 *
 * OutboxEvent остаётся единственной outbox-таблицей (ARCH-3). Механизм
 * MessageTask (GuaranteeMessageTaskMiddleware + message_tasks) не используется
 * бизнес-кодом (ни один dispatch не ставит GuaranteeIdStamp) — дублирующий
 * механизм с отдельной таблицей. Таблица message_tasks больше не нужна.
 */
final class Version20260812203441 extends AbstractMigration
{
    public function getDescription(): string
    {
        return 'Drop unused message_tasks table (P1: single outbox = OutboxEvent)';
    }

    public function up(Schema $schema): void
    {
        $this->addSql('DROP TABLE message_tasks');
    }

    public function down(Schema $schema): void
    {
        $this->addSql('CREATE TABLE message_tasks (id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL, message TEXT NOT NULL, type VARCHAR(255) NOT NULL, status VARCHAR(30) DEFAULT \'new\' NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, updated_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, last_error_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, last_error TEXT DEFAULT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX idx_message_tasks_status ON message_tasks (status)');
    }
}
