<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Партиционирование audit_log по месяцам.
 *
 * Журнал append-only и никогда не чистится — при целевом объёме это 20 млн
 * строк. Партиционирования не было вообще (в pg_class не было ни одной
 * relkind='p'), хотя operations/observability.md §4 и алерт
 * TenderPartitionSizeHigh уже считали «размер партиций audit/auction_bids»:
 * мониторинг предполагал партиции, которых в схеме не существовало.
 *
 * RANGE по created_at, партиция на месяц. Что это даёт: retention и архивация
 * становятся DETACH/DROP одной партиции вместо DELETE по 20 млн строк с
 * последующим VACUUM; чтения с фильтром по периоду отсекают ненужные месяцы
 * (partition pruning); индексы строятся помесячно и не деградируют вместе
 * с общим объёмом. Делается сейчас, пока в таблице тысячи строк, а не потом
 * на миллионах — это ровно тот случай, когда цена миграции растёт со временем.
 *
 * Ключ партиционирования обязан входить в PRIMARY KEY, поэтому PK становится
 * (id, created_at). Для приложения это ничего не меняет: id остаётся
 * уникальным (одна identity-последовательность на всю таблицу), Doctrine
 * читает его через lastval() и по составному ключу не ходит — маппинг
 * сущности не трогается.
 *
 * DEFAULT-партиция обязательна: без неё INSERT в месяц, для которого партиции
 * нет, падает — а падение записи аудита валит саму мутацию (аудит пишется в
 * одной транзакции с ней). Заранее нарезанные месяцы (+12) и команда
 * `db:partitions:ensure` из планировщика держат DEFAULT пустой; DEFAULT — это
 * страховка от отказа, а не рабочий режим.
 */
final class Version20260822170000 extends AbstractMigration
{
    public function getDescription(): string
    {
        return 'Partition audit_log by month (RANGE on created_at) with a DEFAULT catch-all partition';
    }

    public function up(Schema $schema): void
    {
        $this->addSql('ALTER TABLE audit_log RENAME TO audit_log_legacy');
        $this->addSql('ALTER INDEX idx_audit_tenant_entity RENAME TO idx_audit_tenant_entity_legacy');
        $this->addSql('ALTER INDEX idx_audit_created RENAME TO idx_audit_created_legacy');

        $this->addSql(<<<'SQL'
            CREATE TABLE audit_log (
                id          BIGINT GENERATED BY DEFAULT AS IDENTITY,
                tenant_id   VARCHAR(36) DEFAULT NULL,
                actor_type  VARCHAR(20) NOT NULL,
                actor_id    VARCHAR(36) DEFAULT NULL,
                action      VARCHAR(100) NOT NULL,
                entity_type VARCHAR(50) NOT NULL,
                entity_id   VARCHAR(36) NOT NULL,
                before      JSON DEFAULT NULL,
                after       JSON DEFAULT NULL,
                created_at  TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL,
                ip          VARCHAR(45) DEFAULT NULL,
                request_id  VARCHAR(36) DEFAULT NULL,
                timezone    VARCHAR(50) DEFAULT 'UTC' NOT NULL,
                PRIMARY KEY (id, created_at)
            ) PARTITION BY RANGE (created_at)
            SQL);

        // Месяцы от самой ранней существующей записи до +12 месяцев вперёд.
        $this->addSql(<<<'SQL'
            DO $$
            DECLARE
                month_start DATE := date_trunc('month', COALESCE((SELECT min(created_at) FROM audit_log_legacy), now()))::date;
                horizon     DATE := (date_trunc('month', now()) + interval '12 months')::date;
            BEGIN
                WHILE month_start < horizon LOOP
                    EXECUTE format(
                        'CREATE TABLE IF NOT EXISTS %I PARTITION OF audit_log FOR VALUES FROM (%L) TO (%L)',
                        'audit_log_' || to_char(month_start, 'YYYY_MM'),
                        month_start,
                        (month_start + interval '1 month')::date
                    );
                    month_start := (month_start + interval '1 month')::date;
                END LOOP;
            END
            $$
            SQL);

        $this->addSql('CREATE TABLE audit_log_default PARTITION OF audit_log DEFAULT');

        $this->addSql(<<<'SQL'
            INSERT INTO audit_log (id, tenant_id, actor_type, actor_id, action, entity_type, entity_id,
                                   before, after, created_at, ip, request_id, timezone)
            SELECT id, tenant_id, actor_type, actor_id, action, entity_type, entity_id,
                   before, after, created_at, ip, request_id, timezone
            FROM audit_log_legacy
            SQL);

        // Перенос выполнялся с явными id — последовательность нужно подвинуть
        // за максимум, иначе первый же INSERT приложения упрётся в дубль.
        $this->addSql(<<<'SQL'
            SELECT setval(
                pg_get_serial_sequence('audit_log', 'id'),
                GREATEST((SELECT COALESCE(max(id), 0) FROM audit_log), 1)
            )
            SQL);

        $this->addSql('CREATE INDEX idx_audit_tenant_entity ON audit_log (tenant_id, entity_type, entity_id)');
        $this->addSql('CREATE INDEX idx_audit_created ON audit_log (created_at)');

        $this->addSql('DROP TABLE audit_log_legacy');
    }

    public function down(Schema $schema): void
    {
        $this->addSql('ALTER TABLE audit_log RENAME TO audit_log_partitioned');
        $this->addSql('ALTER INDEX idx_audit_tenant_entity RENAME TO idx_audit_tenant_entity_partitioned');
        $this->addSql('ALTER INDEX idx_audit_created RENAME TO idx_audit_created_partitioned');

        $this->addSql(<<<'SQL'
            CREATE TABLE audit_log (
                id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                tenant_id   VARCHAR(36) DEFAULT NULL,
                actor_type  VARCHAR(20) NOT NULL,
                actor_id    VARCHAR(36) DEFAULT NULL,
                action      VARCHAR(100) NOT NULL,
                entity_type VARCHAR(50) NOT NULL,
                entity_id   VARCHAR(36) NOT NULL,
                before      JSON DEFAULT NULL,
                after       JSON DEFAULT NULL,
                created_at  TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL,
                ip          VARCHAR(45) DEFAULT NULL,
                request_id  VARCHAR(36) DEFAULT NULL,
                timezone    VARCHAR(50) DEFAULT 'UTC' NOT NULL
            )
            SQL);

        $this->addSql(<<<'SQL'
            INSERT INTO audit_log (id, tenant_id, actor_type, actor_id, action, entity_type, entity_id,
                                   before, after, created_at, ip, request_id, timezone)
            SELECT id, tenant_id, actor_type, actor_id, action, entity_type, entity_id,
                   before, after, created_at, ip, request_id, timezone
            FROM audit_log_partitioned
            SQL);

        $this->addSql(<<<'SQL'
            SELECT setval(
                pg_get_serial_sequence('audit_log', 'id'),
                GREATEST((SELECT COALESCE(max(id), 0) FROM audit_log), 1)
            )
            SQL);

        $this->addSql('CREATE INDEX idx_audit_tenant_entity ON audit_log (tenant_id, entity_type, entity_id)');
        $this->addSql('CREATE INDEX idx_audit_created ON audit_log (created_at)');

        $this->addSql('DROP TABLE audit_log_partitioned');
    }
}
