<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20260808143627 extends AbstractMigration
{
    public function getDescription(): string
    {
        return '';
    }

    public function up(Schema $schema): void
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->addSql('CREATE TABLE audit_log (id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL, tenant_id VARCHAR(36) DEFAULT NULL, actor_type VARCHAR(20) NOT NULL, actor_id VARCHAR(36) DEFAULT NULL, action VARCHAR(100) NOT NULL, entity_type VARCHAR(50) NOT NULL, entity_id VARCHAR(36) NOT NULL, before JSON DEFAULT NULL, after JSON DEFAULT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, ip VARCHAR(45) DEFAULT NULL, request_id VARCHAR(36) DEFAULT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX idx_audit_tenant_entity ON audit_log (tenant_id, entity_type, entity_id)');
        $this->addSql('CREATE INDEX idx_audit_created ON audit_log (created_at)');
        $this->addSql('CREATE TABLE outbox_events (id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL, event_type VARCHAR(50) NOT NULL, payload JSON NOT NULL, aggregate_type VARCHAR(50) NOT NULL, aggregate_id VARCHAR(36) NOT NULL, status VARCHAR(20) DEFAULT \'pending\' NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, published_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX idx_outbox_status_created ON outbox_events (status, created_at)');
    }

    public function down(Schema $schema): void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->addSql('DROP TABLE audit_log');
        $this->addSql('DROP TABLE outbox_events');
    }
}
