<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20260808160025 extends AbstractMigration
{
    public function getDescription(): string
    {
        return '';
    }

    public function up(Schema $schema): void
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->addSql('CREATE TABLE contract_types (id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL, code VARCHAR(100) NOT NULL, name VARCHAR(200) NOT NULL, default_scope VARCHAR(20) DEFAULT \'single_use\' NOT NULL, description VARCHAR(500) DEFAULT NULL, active BOOLEAN NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_1A31151477153098 ON contract_types (code)');
        $this->addSql('CREATE TABLE document_types (id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL, code VARCHAR(100) NOT NULL, name VARCHAR(200) NOT NULL, description VARCHAR(500) DEFAULT NULL, owner_role VARCHAR(20) NOT NULL, visibility VARCHAR(20) NOT NULL, required BOOLEAN NOT NULL, auto_generated BOOLEAN NOT NULL, active BOOLEAN NOT NULL, sort_order INT NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_3091FF4277153098 ON document_types (code)');
        $this->addSql('CREATE TABLE permissions (id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL, code VARCHAR(100) NOT NULL, name VARCHAR(200) NOT NULL, "group" VARCHAR(20) NOT NULL, description VARCHAR(500) DEFAULT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_2DEDCC6F77153098 ON permissions (code)');
    }

    public function down(Schema $schema): void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->addSql('DROP TABLE contract_types');
        $this->addSql('DROP TABLE document_types');
        $this->addSql('DROP TABLE permissions');
    }
}
