<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Role permissions для manager/agent (FR-1.5.10/1.5.15).
 *
 * 1. Создаёт таблицу role_permissions (unique role+permission_code);
 * 2. Доводит каталог permissions до полного списка из domain/permissions.md
 *    (первый seed 0.8 содержал 15 кодов и 3 неканонических: tenders.rating,
 *    auctions.join, platform.users.manage — удаляются за ненадобностью);
 * 3. Сеет default-матрицу для manager/agent (is_default=true) из
 *    domain/permissions.md. ON CONFLICT DO NOTHING — суперадмин-оверрайды
 *    (is_default=false) не перетираются.
 *
 * admin — фиксированный полный набор, в role_permissions не хранится.
 */
final class Version20260810100000 extends AbstractMigration
{
    public function getDescription(): string
    {
        return 'Create role_permissions, expand permissions catalog, seed default matrices';
    }

    public function up(Schema $schema): void
    {
        $this->addSql('CREATE TABLE role_permissions (id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL, role VARCHAR(20) NOT NULL, permission_code VARCHAR(100) NOT NULL, enabled BOOLEAN NOT NULL, is_default BOOLEAN NOT NULL, updated_by UUID DEFAULT NULL, updated_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_ROLE_PERMISSIONS_ROLE_CODE ON role_permissions (role, permission_code)');

        // --- 1. Полный каталог разрешений (domain/permissions.md) ---
        $catalog = [
            // common
            ['profile.view', 'Просмотр своего профиля', 'common'],
            ['profile.update', 'Обновление своего профиля', 'common'],
            ['tenders.board.view', 'Просмотр доски тендеров', 'common'],
            // customer
            ['tenders.create', 'Создание тендера/лотов', 'customer'],
            ['tenders.publish', 'Публикация тендера', 'customer'],
            ['tenders.update', 'Изменение тендера', 'customer'],
            ['tenders.withdraw', 'Отзыв публикации (withdrawn)', 'customer'],
            ['tenders.cancel', 'Отмена тендера (причина)', 'customer'],
            ['tenders.manage_docs', 'Документация тендера', 'customer'],
            ['tenders.qa', 'Вопросы/ответы', 'customer'],
            ['bids.qualify', 'Допуск/отклонение заявок', 'customer'],
            ['auction.control', 'Пауза/остановка аукциона', 'customer'],
            ['auction.choose_winner', 'Выбор победителя', 'customer'],
            ['contracts.create', 'Создание договора', 'customer'],
            ['contracts.sign', 'Подписание договора', 'customer'],
            ['claims.manage', 'Создание/урегулирование претензий', 'customer'],
            ['tenders.rate', 'Оценка исполнения', 'customer'],
            // supplier
            ['bids.draft_prepare', 'Подготовка черновиков заявок', 'supplier'],
            ['bids.submit', 'Подача заявки', 'supplier'],
            ['bids.withdraw', 'Отзыв заявки', 'supplier'],
            ['auction.bid', 'Ставки в аукционе', 'supplier'],
            ['execution.manage', 'Этапы исполнения, DONE_BY_PERFORMER', 'supplier'],
            ['contracts.scan_upload', 'Скан договора', 'supplier'],
            ['claims.respond', 'Ответ на претензию', 'supplier'],
            // platform
            ['users.manage', 'Управление пользователями компании', 'platform'],
            ['org.settings', 'Настройки компании', 'platform'],
            ['platform.timezone.manage', 'Управление доменным часовым поясом', 'platform'],
            ['api_keys.manage', 'API-ключи', 'platform'],
            ['webhooks.manage', 'Webhook-подписки', 'platform'],
        ];
        foreach ($catalog as [$code, $name, $group]) {
            $this->addSql(
                'INSERT INTO permissions (code, name, "group", created_at) VALUES (:code, :name, :group, NOW())
                 ON CONFLICT (code) DO NOTHING',
                ['code' => $code, 'name' => $name, 'group' => $group],
            );
        }

        // --- 2. Удаление неканонических кодов из seed 0.8 ---
        $this->addSql(
            "DELETE FROM permissions WHERE code IN ('tenders.rating','auctions.join','platform.users.manage')",
        );

        // --- 3. Default-матрица manager/agent (domain/permissions.md) ---
        $defaults = [
            'manager' => [
                'profile.view' => true, 'profile.update' => true, 'tenders.board.view' => true,
                'tenders.create' => true, 'tenders.publish' => true, 'tenders.update' => true,
                'tenders.withdraw' => true, 'tenders.cancel' => true, 'tenders.manage_docs' => true,
                'tenders.qa' => true, 'bids.qualify' => true, 'auction.control' => true,
                'auction.choose_winner' => true, 'contracts.create' => true, 'contracts.sign' => true,
                'claims.manage' => true, 'tenders.rate' => true,
                'bids.draft_prepare' => true, 'bids.submit' => true, 'bids.withdraw' => true,
                'auction.bid' => true, 'execution.manage' => true, 'contracts.scan_upload' => true,
                'claims.respond' => true,
                'users.manage' => false, 'org.settings' => false, 'platform.timezone.manage' => false,
                'api_keys.manage' => false, 'webhooks.manage' => false,
            ],
            'agent' => [
                'profile.view' => true, 'profile.update' => true, 'tenders.board.view' => true,
                'tenders.create' => false, 'tenders.publish' => false, 'tenders.update' => false,
                'tenders.withdraw' => false, 'tenders.cancel' => false, 'tenders.manage_docs' => true,
                'tenders.qa' => true, 'bids.qualify' => false, 'auction.control' => false,
                'auction.choose_winner' => false, 'contracts.create' => false, 'contracts.sign' => false,
                'claims.manage' => false, 'tenders.rate' => false,
                'bids.draft_prepare' => true, 'bids.submit' => false, 'bids.withdraw' => false,
                'auction.bid' => false, 'execution.manage' => false, 'contracts.scan_upload' => false,
                'claims.respond' => false,
                'users.manage' => false, 'org.settings' => false, 'platform.timezone.manage' => false,
                'api_keys.manage' => false, 'webhooks.manage' => false,
            ],
        ];
        foreach ($defaults as $role => $codes) {
            foreach ($codes as $code => $enabled) {
                $this->addSql(
                    'INSERT INTO role_permissions (role, permission_code, enabled, is_default, updated_at)
                     VALUES (:role, :code, :enabled, true, NOW())
                     ON CONFLICT (role, permission_code) DO NOTHING',
                    ['role' => $role, 'code' => $code, 'enabled' => $enabled],
                    ['enabled' => \Doctrine\DBAL\Types\Types::BOOLEAN],
                );
            }
        }
    }

    public function down(Schema $schema): void
    {
        $this->addSql('DROP TABLE role_permissions');
        // вернуть неканонические коды (seed 0.8), убрать добавленные
        $this->addSql("INSERT INTO permissions (code, name, \"group\", created_at) VALUES
            ('tenders.rating','Оценка исполнения','customer',NOW()),
            ('auctions.join','Участие в аукционе','supplier',NOW()),
            ('platform.users.manage','Управление пользователями','platform',NOW())
            ON CONFLICT (code) DO NOTHING");
    }
}
