<?php

declare(strict_types=1);

namespace App\Document\Input;

/**
 * Входные данные создания типа документа (FR-1.2.7, POST /document-types).
 * code — уникальный код; name — наименование; owner_role — сторона-владелец;
 * visibility — видимость по умолчанию; required — обязательность;
 * auto_generated — тип создан плагином (DocumentGenerator), в ядре — false.
 */
final class CreateDocumentTypeInput
{
    /** Обязательное поле (NotBlank в форме) — не может быть null при валидной форме. */
    public string $code = '';
    /** Обязательное поле (NotBlank в форме) — не может быть null при валидной форме. */
    public string $name = '';
    /** Обязательное поле (NotBlank в форме) — не может быть null при валидной форме. */
    public string $ownerRole = '';
    /** Обязательное поле (NotBlank в форме) — не может быть null при валидной форме. */
    public string $visibility = '';
    public bool $required = false;
    public bool $autoGenerated = false;
}
