<?php

declare(strict_types=1);

namespace App\Document;

use App\Document\Entity\Document;
use App\Document\Entity\DocumentType;
use App\Document\Entity\DocumentVersion;

/**
 * Публичное представление документа и типа документа (openapi schemas
 * Document / DocumentType). Деньги не участвуют; пути скачивания формируются
 * контроллером (download_url).
 */
final readonly class DocumentPresenter
{
    /**
     * Route скачивания текущей версии (AM-8, GET /documents/{id}/download).
     * Используется UseCase-слоем для построения download_url в презентации;
     * источник пути — DocumentDownloadController::URL (единый шаблон).
     */
    public const string DOWNLOAD_URL = '/api/v1/documents/{documentId}/download';

    /**
     * Полная карточка документа с версиями (openapi Document).
     *
     * @return array<string, mixed>
     */
    public function single(Document $document, ?string $downloadUrl = null): array
    {
        return [
            'id' => (string) $document->getId(),
            'document_type_id' => $document->getDocumentType()->getId(),
            'entity_type' => $document->getEntityType()->value,
            'entity_id' => (string) $document->getEntityId(),
            'title' => $document->getTitle(),
            'owner_role' => $document->getOwnerRole()->value,
            'visibility' => $document->getVisibility()->value,
            'scope' => $document->getScope()->value,
            'is_auto_generated' => $document->isAutoGenerated(),
            'versions' => array_map(
                static fn (DocumentVersion $version): array => [
                    'file_id' => (string) $version->getId(),
                    'version' => $version->getVersion(),
                    'sha256' => $version->getSha256(),
                    'size_bytes' => $version->getSizeBytes(),
                    'uploaded_at' => $version->getUploadedAt()->format('Y-m-d\TH:i:s\Z'),
                ],
                $document->getVersions(),
            ),
            'download_url' => $downloadUrl,
        ];
    }

    /**
     * Представление типа документа (openapi DocumentType).
     *
     * @return array<string, mixed>
     */
    public function type(DocumentType $type): array
    {
        return [
            'id' => $type->getId(),
            'code' => $type->getCode(),
            'name' => $type->getName(),
            'owner_role' => $type->getOwnerRole(),
            'visibility' => $type->getVisibility(),
            'required' => $type->isRequired(),
            'auto_generated' => $type->isAutoGenerated(),
            'active' => $type->isActive(),
        ];
    }
}
