<?php

declare(strict_types=1);

namespace App\Document\Entity;

use App\Document\Entity\Enum\DocumentEntityType;
use App\Document\Entity\Enum\DocumentOwnerRole;
use App\Document\Entity\Enum\DocumentScope;
use App\Document\Entity\Enum\DocumentVisibility;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;
use Symfony\Component\Uid\Uuid;

/**
 * Документ (AM-8, FR-1.1.5/1.2.6/1.2.7). Агрегат версий (DocumentVersion):
 * каждая загрузка того же файла-документа создаёт новую версию с собственным
 * file_id (DocumentVersion.id), sha256 и размером. Актуальная версия — последняя
 * по порядку version.
 *
 * Видимость (FR-1.2.6): public — всем допущенным участникам; private — владельцу
 * и победителю. owner_role — сторона-владелец (customer/executor/system).
 * scope — tender или contract (AM-8). is_auto_generated — только через плагин
 * (DocumentGenerator, FR-1.2.8); в ядре всегда false.
 *
 * Tenant-изоляция: tenant_id фиксируется при создании (компания актора);
 * доступ к документу разрешается только в рамках своей компании (плюс правила
 * видимости FR-1.2.6).
 */
#[ORM\Entity]
#[ORM\Table(name: 'documents')]
#[ORM\Index(name: 'idx_documents_entity', columns: ['entity_type', 'entity_id'])]
#[ORM\Index(name: 'idx_documents_tenant', columns: ['tenant_id'])]
class Document
{
    #[ORM\Id]
    #[ORM\Column(type: 'uuid', unique: true)]
    private Uuid $id;

    #[ORM\ManyToOne(targetEntity: DocumentType::class)]
    #[ORM\JoinColumn(name: 'document_type_id', referencedColumnName: 'id', nullable: false)]
    private DocumentType $documentType;

    #[ORM\Column(type: 'string', length: 20, enumType: DocumentEntityType::class)]
    private DocumentEntityType $entityType;

    #[ORM\Column(type: 'uuid')]
    private Uuid $entityId;

    #[ORM\Column(length: 500)]
    private string $title;

    #[ORM\Column(type: 'string', length: 20, enumType: DocumentOwnerRole::class)]
    private DocumentOwnerRole $ownerRole;

    #[ORM\Column(type: 'string', length: 20, enumType: DocumentVisibility::class)]
    private DocumentVisibility $visibility;

    #[ORM\Column(type: 'string', length: 20, enumType: DocumentScope::class)]
    private DocumentScope $scope;

    #[ORM\Column]
    private bool $isAutoGenerated = false;

    #[ORM\Column(type: 'uuid')]
    private Uuid $tenantId;

    #[ORM\Column(type: 'uuid')]
    private Uuid $createdBy;

    #[ORM\Column(type: 'datetime_immutable')]
    private \DateTimeImmutable $createdAt;

    /** @var Collection<int, DocumentVersion> */
    #[ORM\OneToMany(targetEntity: DocumentVersion::class, mappedBy: 'document', cascade: ['persist', 'remove'], orphanRemoval: true)]
    #[ORM\OrderBy(['version' => 'ASC'])]
    private Collection $versions;

    public function __construct(
        DocumentType $documentType,
        DocumentEntityType $entityType,
        Uuid $entityId,
        string $title,
        DocumentOwnerRole $ownerRole,
        DocumentVisibility $visibility,
        DocumentScope $scope,
        Uuid $tenantId,
        Uuid $createdBy,
    ) {
        $this->id = Uuid::v4();
        $this->documentType = $documentType;
        $this->entityType = $entityType;
        $this->entityId = $entityId;
        $this->title = $title;
        $this->ownerRole = $ownerRole;
        $this->visibility = $visibility;
        $this->scope = $scope;
        $this->tenantId = $tenantId;
        $this->createdBy = $createdBy;
        $this->createdAt = new \DateTimeImmutable('now', new \DateTimeZone('UTC'));
        $this->versions = new ArrayCollection();
    }

    public function getId(): Uuid
    {
        return $this->id;
    }

    public function getDocumentType(): DocumentType
    {
        return $this->documentType;
    }

    public function getEntityType(): DocumentEntityType
    {
        return $this->entityType;
    }

    public function getEntityId(): Uuid
    {
        return $this->entityId;
    }

    public function getTitle(): string
    {
        return $this->title;
    }

    public function getOwnerRole(): DocumentOwnerRole
    {
        return $this->ownerRole;
    }

    public function getVisibility(): DocumentVisibility
    {
        return $this->visibility;
    }

    public function getScope(): DocumentScope
    {
        return $this->scope;
    }

    public function isAutoGenerated(): bool
    {
        return $this->isAutoGenerated;
    }

    public function getTenantId(): Uuid
    {
        return $this->tenantId;
    }

    public function getCreatedBy(): Uuid
    {
        return $this->createdBy;
    }

    public function getCreatedAt(): \DateTimeImmutable
    {
        return $this->createdAt;
    }

    /**
     * @return list<DocumentVersion>
     */
    public function getVersions(): array
    {
        /** @var list<DocumentVersion> */
        return $this->versions->toArray();
    }

    public function setAutoGenerated(bool $autoGenerated): void
    {
        $this->isAutoGenerated = $autoGenerated;
    }

    public function currentVersion(): ?DocumentVersion
    {
        $current = null;
        foreach ($this->versions as $version) {
            if (null === $current || $version->getVersion() > $current->getVersion()) {
                $current = $version;
            }
        }

        return $current;
    }

    public function nextVersionNumber(): int
    {
        $max = 0;
        foreach ($this->versions as $version) {
            $max = max($max, $version->getVersion());
        }

        return $max + 1;
    }

    public function addVersion(DocumentVersion $version): void
    {
        if (!$this->versions->contains($version)) {
            $this->versions->add($version);
        }
    }
}
