<?php

declare(strict_types=1);

namespace App\Document\Entity;

use Doctrine\ORM\Mapping as ORM;

/**
 * Тип документа (справочник, FR-1.2.7, управляется суперадмином).
 * Стартовый набор: скан договора (executor, private), документы заявки
 * (executor), документация тендера (customer, public). auto_generated-типы
 * добавляются только плагинами (контракт DocumentGenerator, FR-1.2.8).
 */
#[ORM\Entity]
#[ORM\Table(name: 'document_types')]
class DocumentType
{
    #[ORM\Id]
    #[ORM\Column(type: 'bigint', options: ['unsigned' => true])]
    #[ORM\GeneratedValue]
    /** @var int|null Doctrine присваивает id через reflection */
    private ?int $id = null;

    #[ORM\Column(length: 100, unique: true)]
    private string $code;

    #[ORM\Column(length: 200)]
    private string $name;

    #[ORM\Column(length: 500, nullable: true)]
    private ?string $description = null;

    #[ORM\Column(length: 20)]
    private string $ownerRole;

    #[ORM\Column(length: 20)]
    private string $visibility;

    #[ORM\Column]
    private bool $required = false;

    #[ORM\Column]
    private bool $autoGenerated = false;

    #[ORM\Column]
    private bool $active = true;

    #[ORM\Column]
    private int $sortOrder = 0;

    #[ORM\Column(type: 'datetime_immutable')]
    private \DateTimeImmutable $createdAt;

    public function __construct(
        string $code,
        string $name,
        string $ownerRole,
        string $visibility,
        bool $required = false,
        int $sortOrder = 0,
        ?string $description = null,
    ) {
        $this->code = $code;
        $this->name = $name;
        $this->ownerRole = $ownerRole;
        $this->visibility = $visibility;
        $this->required = $required;
        $this->sortOrder = $sortOrder;
        $this->description = $description;
        $this->createdAt = new \DateTimeImmutable('now', new \DateTimeZone('UTC'));
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getCode(): string
    {
        return $this->code;
    }

    public function getName(): string
    {
        return $this->name;
    }

    public function getOwnerRole(): string
    {
        return $this->ownerRole;
    }

    public function getVisibility(): string
    {
        return $this->visibility;
    }

    public function isRequired(): bool
    {
        return $this->required;
    }

    public function isAutoGenerated(): bool
    {
        return $this->autoGenerated;
    }

    public function isActive(): bool
    {
        return $this->active;
    }

    public function getSortOrder(): int
    {
        return $this->sortOrder;
    }

    public function getDescription(): ?string
    {
        return $this->description;
    }

    public function getCreatedAt(): \DateTimeImmutable
    {
        return $this->createdAt;
    }

    public function setName(string $name): void
    {
        $this->name = $name;
    }

    public function setOwnerRole(string $ownerRole): void
    {
        $this->ownerRole = $ownerRole;
    }

    public function setVisibility(string $visibility): void
    {
        $this->visibility = $visibility;
    }

    public function setRequired(bool $required): void
    {
        $this->required = $required;
    }

    public function setAutoGenerated(bool $autoGenerated): void
    {
        $this->autoGenerated = $autoGenerated;
    }

    public function setActive(bool $active): void
    {
        $this->active = $active;
    }
}
