<?php

declare(strict_types=1);

namespace App\Tests\Integration\RuStateProcurement;

use App\Document\DocumentGenerator;
use App\Document\Entity\Document;
use App\Document\Entity\Enum\DocumentEntityType;
use App\Document\Entity\Enum\DocumentOwnerRole;
use App\Document\Entity\Enum\DocumentVisibility;
use App\Document\Storage\FileStorage;
use App\RuStateProcurement\Config\ProcurementConfig;
use App\Shared\Exception\ConflictException;
use App\Tender\Entity\Enum\ProcedureTypeEnum;
use App\Tests\Factory\DocumentTypeFactory;
use App\Tests\Factory\LotFactory;
use App\Tests\Factory\TenderFactory;
use Doctrine\ORM\EntityManagerInterface;
use Symfony\Bundle\FrameworkBundle\Test\KernelTestCase;

/**
 * Контракт авто-генерации документов ядра (FR-1.2.8): идемпотентная
 * регистрация auto_generated-типов, создание документов от имени системы
 * (owner_role=system, is_auto_generated=true), идемпотентность повторов,
 * отказ для не-auto_generated-типов.
 */
final class RuDocumentGeneratorTest extends KernelTestCase
{
    private DocumentGenerator $generator;
    private EntityManagerInterface $em;
    private FileStorage $storage;

    protected function setUp(): void
    {
        self::bootKernel();
        $container = self::getContainer();

        $generator = $container->get(DocumentGenerator::class);
        self::assertInstanceOf(DocumentGenerator::class, $generator);
        $this->generator = $generator;

        $this->em = $container->get(EntityManagerInterface::class);
        $this->storage = $container->get(FileStorage::class);
    }

    public function testEnsureDocumentTypeIsIdempotent(): void
    {
        $first = $this->generator->ensureDocumentType('protocol_opening', 'Протокол вскрытия', DocumentOwnerRole::SYSTEM, DocumentVisibility::PUBLIC);
        $second = $this->generator->ensureDocumentType('protocol_opening', 'Протокол вскрытия', DocumentOwnerRole::SYSTEM, DocumentVisibility::PUBLIC);

        self::assertSame($first->getId(), $second->getId());
        self::assertTrue($second->isAutoGenerated());
        self::assertSame('system', $second->getOwnerRole());
        self::assertSame('public', $second->getVisibility());
    }

    public function testGenerateCreatesSystemDocumentWithContent(): void
    {
        $this->generator->ensureDocumentType('protocol_test', 'Тестовый протокол', DocumentOwnerRole::SYSTEM, DocumentVisibility::PUBLIC);
        $tender = TenderFactory::createOne(['procedureType' => ProcedureTypeEnum::AUCTION]);
        LotFactory::createOne(['tender' => $tender]);
        $content = "ПРОТОКОЛ ТЕСТ\nСодержимое";

        $document = $this->generator->generate(
            documentTypeCode: 'protocol_test',
            entityType: DocumentEntityType::TENDER,
            entityId: $tender->getId(),
            title: 'Протокол тест',
            content: $content,
            mimeType: 'text/plain',
            extension: 'txt',
            tenantId: $tender->getTenantId(),
            visibility: DocumentVisibility::PUBLIC,
        );

        self::assertTrue($document->isAutoGenerated());
        self::assertSame(DocumentOwnerRole::SYSTEM, $document->getOwnerRole());
        self::assertSame(DocumentVisibility::PUBLIC, $document->getVisibility());
        self::assertSame(DocumentEntityType::TENDER, $document->getEntityType());
        self::assertSame($tender->getTenantId()->toRfc4122(), $document->getTenantId()->toRfc4122());

        $version = $document->currentVersion();
        self::assertNotNull($version);
        self::assertSame(hash('sha256', $content), $version->getSha256());
        self::assertSame('text/plain', $version->getMimeType());
        self::assertSame($content, $this->storage->read($version->getStoragePath()));

        $this->em->clear();
        $reloaded = $this->em->getRepository(Document::class)->find((string) $document->getId());
        self::assertNotNull($reloaded);
        self::assertTrue($reloaded->isAutoGenerated());
    }

    public function testGenerateIsIdempotent(): void
    {
        $this->generator->ensureDocumentType('protocol_opening', 'Протокол вскрытия', DocumentOwnerRole::SYSTEM, DocumentVisibility::PUBLIC);
        $tender = TenderFactory::createOne(['procedureType' => ProcedureTypeEnum::AUCTION]);

        $first = $this->generator->generate(
            documentTypeCode: 'protocol_opening',
            entityType: DocumentEntityType::TENDER,
            entityId: $tender->getId(),
            title: 'Протокол вскрытия T-1',
            content: 'ПРОТОКОЛ ВСКРЫТИЯ',
            mimeType: 'text/plain',
            extension: 'txt',
            tenantId: $tender->getTenantId(),
            visibility: DocumentVisibility::PUBLIC,
        );
        $second = $this->generator->generate(
            documentTypeCode: 'protocol_opening',
            entityType: DocumentEntityType::TENDER,
            entityId: $tender->getId(),
            title: 'Протокол вскрытия T-1',
            content: 'ПРОТОКОЛ ВСКРЫТИЯ',
            mimeType: 'text/plain',
            extension: 'txt',
            tenantId: $tender->getTenantId(),
            visibility: DocumentVisibility::PUBLIC,
        );

        self::assertSame($first->getId()->toRfc4122(), $second->getId()->toRfc4122());
        $count = $this->em->getConnection()->executeQuery(
            "SELECT COUNT(*) FROM documents WHERE entity_type = 'tender' AND entity_id = :id",
            ['id' => $tender->getId()->toRfc4122()],
        )->fetchOne();
        self::assertIsNumeric($count);
        self::assertSame(1, (int) $count);
    }

    public function testGenerateRejectsUnknownType(): void
    {
        $tender = TenderFactory::createOne();

        $this->expectException(ConflictException::class);
        $this->generator->generate(
            documentTypeCode: 'unknown_protocol',
            entityType: DocumentEntityType::TENDER,
            entityId: $tender->getId(),
            title: 'Протокол',
            content: 'content',
            mimeType: 'text/plain',
            extension: 'txt',
            tenantId: $tender->getTenantId(),
        );
    }

    public function testGenerateRejectsNonAutoGeneratedType(): void
    {
        // Админский справочник: auto_generated=false — только через плагин (FR-1.2.8).
        $type = DocumentTypeFactory::createOne(['code' => 'manual_doc', 'ownerRole' => 'customer']);
        $tender = TenderFactory::createOne();

        $this->expectException(ConflictException::class);
        $this->generator->generate(
            documentTypeCode: 'manual_doc',
            entityType: DocumentEntityType::TENDER,
            entityId: $tender->getId(),
            title: 'Протокол',
            content: 'content',
            mimeType: 'text/plain',
            extension: 'txt',
            tenantId: $tender->getTenantId(),
        );

        self::assertSame('manual_doc', $type->getCode());
    }

    public function testConfigIsInjectible(): void
    {
        $config = self::getContainer()->get(ProcurementConfig::class);
        self::assertInstanceOf(ProcurementConfig::class, $config);
        self::assertSame(600, $config->auctionStepDurationSec());
    }
}
