<?php

declare(strict_types=1);

namespace App\Tests\Integration\RuStateProcurement;

use App\Document\Entity\Document;
use App\Document\Entity\Enum\DocumentEntityType;
use App\Document\Entity\Enum\DocumentOwnerRole;
use App\Document\Storage\FileStorage;
use App\RuStateProcurement\Protocol\RuProtocolGenerator;
use App\Shared\Events\EventMessage;
use App\Tests\Factory\AuctionFactory;
use App\Tests\Factory\LotFactory;
use App\Tests\Factory\TenderFactory;
use Doctrine\ORM\EntityManagerInterface;
use Symfony\Bundle\FrameworkBundle\Test\KernelTestCase;
use Symfony\Component\Uid\Uuid;

/**
 * «Протоколы через DocumentGenerator» (7.7, FR-1.2.8): плагин
 * ru-state-procurement генерирует протоколы от имени системы из событий ядра
 * (tender.opened → протокол вскрытия; auction.winner_chosen → итоговый),
 * прикладывает их к тендеру (owner_role=system, auto_generated).
 */
final class RuProtocolGeneratorTest extends KernelTestCase
{
    private RuProtocolGenerator $protocols;
    private EntityManagerInterface $em;
    private FileStorage $storage;

    protected function setUp(): void
    {
        self::bootKernel();
        $container = self::getContainer();

        $protocols = $container->get(RuProtocolGenerator::class);
        self::assertInstanceOf(RuProtocolGenerator::class, $protocols);
        $this->protocols = $protocols;

        $this->em = $container->get(EntityManagerInterface::class);
        $this->storage = $container->get(FileStorage::class);
    }

    public function testOpeningProtocolGeneratedFromTenderOpenedEvent(): void
    {
        $tender = TenderFactory::createOne(['number' => 'T-RU-77']);
        LotFactory::createOne(['tender' => $tender]);

        $documentId = $this->protocols->generateOpeningProtocol(EventMessage::create(
            eventType: 'tender.opened',
            tenantId: (string) $tender->getTenantId(),
            aggregateType: 'tender',
            aggregateId: (string) $tender->getId(),
            payload: [
                'tender_id' => (string) $tender->getId(),
                'number' => $tender->getNumber(),
                'bids_end' => '2026-08-20T10:00:00Z',
                'bids_count' => 3,
                'opened_at' => '2026-08-20T10:05:00Z',
            ],
        ));

        self::assertNotNull($documentId);
        $document = $this->em->getRepository(Document::class)->find($documentId);
        self::assertNotNull($document);
        self::assertSame('protocol_opening', $document->getDocumentType()->getCode());
        self::assertTrue($document->isAutoGenerated());
        self::assertSame(DocumentOwnerRole::SYSTEM, $document->getOwnerRole());
        self::assertSame(DocumentEntityType::TENDER, $document->getEntityType());
        self::assertSame($tender->getTenantId()->toRfc4122(), $document->getTenantId()->toRfc4122());

        $version = $document->currentVersion();
        self::assertNotNull($version);
        $content = $this->storage->read($version->getStoragePath());
        self::assertStringContainsString('ПРОТОКОЛ ВСКРЫТИЯ ЗАЯВОК', $content);
        self::assertStringContainsString('T-RU-77', $content);
        self::assertStringContainsString('3', $content);
    }

    public function testFinalProtocolGeneratedFromWinnerChosenEvent(): void
    {
        $tender = TenderFactory::createOne(['number' => 'T-RU-88']);
        $auction = AuctionFactory::new()->forTender($tender)->create();

        $documentId = $this->protocols->generateFinalProtocol(EventMessage::create(
            eventType: 'auction.winner_chosen',
            tenantId: (string) $tender->getTenantId(),
            aggregateType: 'auction',
            aggregateId: (string) $auction->getId(),
            payload: [
                'auction_id' => (string) $auction->getId(),
                'supplier_id' => (string) Uuid::v4(),
                'price_minor' => 123456,
                'basis' => 'gross',
                'vat_rate' => 2000,
                'mode' => 'auto',
            ],
        ));

        self::assertNotNull($documentId);
        $document = $this->em->getRepository(Document::class)->find($documentId);
        self::assertNotNull($document);
        self::assertSame('protocol_final', $document->getDocumentType()->getCode());
        self::assertTrue($document->isAutoGenerated());
        self::assertSame(DocumentOwnerRole::SYSTEM, $document->getOwnerRole());

        $version = $document->currentVersion();
        self::assertNotNull($version);
        $content = $this->storage->read($version->getStoragePath());
        self::assertStringContainsString('ИТОГОВЫЙ ПРОТОКОЛ', $content);
        self::assertStringContainsString('T-RU-88', $content);
        self::assertStringContainsString('1 234,56 ₽', $content);
        self::assertStringContainsString('gross', $content);
        self::assertStringContainsString('НДС 20%', $content);
    }

    public function testRepeatedOpeningEventDoesNotDuplicateDocument(): void
    {
        $tender = TenderFactory::createOne(['number' => 'T-RU-99']);
        $payload = [
            'tender_id' => (string) $tender->getId(),
            'number' => $tender->getNumber(),
            'bids_end' => '2026-08-20T10:00:00Z',
            'bids_count' => 1,
            'opened_at' => '2026-08-20T10:05:00Z',
        ];
        $message = EventMessage::create('tender.opened', (string) $tender->getTenantId(), 'tender', (string) $tender->getId(), $payload);

        $first = $this->protocols->generateOpeningProtocol($message);
        $second = $this->protocols->generateOpeningProtocol($message);

        self::assertNotNull($first);
        self::assertSame($first, $second);
        $count = $this->em->getConnection()->executeQuery(
            "SELECT COUNT(*) FROM documents WHERE entity_type = 'tender' AND entity_id = :id AND document_type_id = (SELECT id FROM document_types WHERE code = 'protocol_opening')",
            ['id' => $tender->getId()->toRfc4122()],
        )->fetchOne();
        self::assertIsNumeric($count);
        self::assertSame(1, (int) $count);
    }

    public function testEventWithoutTenderSkipsProtocol(): void
    {
        $result = $this->protocols->generateOpeningProtocol(EventMessage::create(
            eventType: 'tender.opened',
            tenantId: (string) Uuid::v4(),
            aggregateType: 'tender',
            aggregateId: (string) Uuid::v4(),
            payload: ['tender_id' => (string) Uuid::v4()],
        ));

        self::assertNull($result);
    }
}
